name: w_module
version: 0.3.0
dependencies:
  app_intelligence:
    path: ../appintelligence/AppIntelligence/
  uuid: 0.5.0
dev_dependencies:
  browser: "^0.10.0+2"
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: "^0.2.0"
  mockito: "^0.10.0"
  react: "0.8.0"
  test: "^0.12.0"
  w_flux: "^1.0.0"
